# Generated by Django 5.2.3 on 2025-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
