# Generated by Django 5.2.8 on 2025-11-19 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_blood_alter_client_gender_and_more'),
        ('creditor', '0002_alter_creditor_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditor',
            options={'verbose_name': 'دائن', 'verbose_name_plural': 'الدائنين'},
        ),
        migrations.AlterField(
            model_name='creditor',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditor', to='client.client', verbose_name='الدائن'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='creditorDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='total',
            field=models.IntegerField(verbose_name='المبلغ'),
        ),
    ]
