# Generated by Django 5.2.3 on 2025-11-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bornYear', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.BooleanField(default=False)),
                ('alergy', models.CharField(blank=True, max_length=200, null=True)),
                ('desiase', models.CharField(blank=True, max_length=200, null=True)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('لا اعرف', 'لا اعرف'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('A-', 'A-')], default='لا اعرف', max_length=20)),
                ('mariage', models.CharField(choices=[('اعزب', 'اعزب'), ('مطلق', 'مطلق'), ('متزوج', 'متزوج'), ('ارمل', 'ارمل')], default='اعزب', max_length=20)),
                ('lastOperations', models.CharField(blank=True, max_length=200, null=True)),
                ('smooker', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
