# Generated by Django 5.2.3 on 2025-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(choices=[('لا اعرف', 'لا اعرف'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A-', 'A-'), ('O+', 'O+')], default='لا اعرف', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='mariage',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('اعزب', 'اعزب'), ('ارمل', 'ارمل')], default='اعزب', max_length=20),
        ),
    ]
