# Generated by Django 5.2.8 on 2025-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_blood_alter_client_mariage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'زبون', 'verbose_name_plural': 'الزبائن'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='alergy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الحساسية'),
        ),
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(choices=[('O-', 'O-'), ('B-', 'B-'), ('A-', 'A-'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('لا اعرف', 'لا اعرف'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='لا اعرف', max_length=20, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bornYear',
            field=models.IntegerField(verbose_name='التولد'),
        ),
        migrations.AlterField(
            model_name='client',
            name='desiase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='امراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='client',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='اخفاء'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastOperations',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عمليات سابقة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mariage',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('اعزب', 'اعزب'), ('ارمل', 'ارمل')], default='اعزب', max_length=20, verbose_name='الحالة الزوجية'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='client',
            name='smooker',
            field=models.BooleanField(default=False, verbose_name='مدخن'),
        ),
    ]
