# Generated by Django 5.2.8 on 2025-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(choices=[('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('B-', 'B-'), ('O+', 'O+'), ('A-', 'A-'), ('لا اعرف', 'لا اعرف'), ('A+', 'A+'), ('AB-', 'AB-')], default='لا اعرف', max_length=20, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='ذكر', verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mariage',
            field=models.CharField(choices=[('ارمل', 'ارمل'), ('اعزب', 'اعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق')], default='اعزب', max_length=20, verbose_name='الحالة الزوجية'),
        ),
    ]
