# Generated by Django 5.2.3 on 2025-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_blood_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(choices=[('لا اعرف', 'لا اعرف'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], default='لا اعرف', max_length=20, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('انثى', 'انثى'), ('ذكر', 'ذكر')], default='ذكر', verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mariage',
            field=models.CharField(choices=[('ارمل', 'ارمل'), ('اعزب', 'اعزب'), ('مطلق', 'مطلق'), ('متزوج', 'متزوج')], default='اعزب', max_length=20, verbose_name='الحالة الزوجية'),
        ),
    ]
