# Generated by Django 5.2.3 on 2025-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_blood_alter_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(choices=[('B-', 'B-'), ('A+', 'A+'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('A-', 'A-'), ('لا اعرف', 'لا اعرف'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='لا اعرف', max_length=20, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mariage',
            field=models.CharField(choices=[('مطلق', 'مطلق'), ('اعزب', 'اعزب'), ('ارمل', 'ارمل'), ('متزوج', 'متزوج')], default='اعزب', max_length=20, verbose_name='الحالة الزوجية'),
        ),
    ]
