# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0001_initial'),
        ('staff', '0003_alter_staff_options_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punishment',
            options={'verbose_name': 'عقوبة', 'verbose_name_plural': 'العقوبات'},
        ),
        migrations.AlterField(
            model_name='punishment',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='تم التنفيذ'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='punishmentDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='reasone',
            field=models.CharField(max_length=200, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PunishmentStaff', to='staff.staff', verbose_name='الموظف'),
        ),
    ]
