# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phonespecialize', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('isBanned', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('totalPercent', models.IntegerField(default=0)),
                ('nextPercent', models.IntegerField(default=0)),
                ('amountThreshold', models.IntegerField(default=0)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('endDate', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
