# Generated by Django 5.2.8 on 2025-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phonespecialize',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='specialize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
