# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_phonespecialize_staff_phone_staff_specialize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='amountThreshold',
            field=models.IntegerField(default=0, verbose_name='مبلغ العتبة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='endDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='مسؤول'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='isBanned',
            field=models.BooleanField(default=False, verbose_name='محظور'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nextPercent',
            field=models.IntegerField(default=0, verbose_name='النسبة بعد مبلغ العتبة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='الراتب'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialize',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='totalPercent',
            field=models.IntegerField(default=0, verbose_name='النسبة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المستخدم'),
        ),
    ]
