# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('service', '0002_alter_service_options_alter_service_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'عرض', 'verbose_name_plural': 'عروضات'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='endDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='newPrice',
            field=models.IntegerField(default=0, verbose_name='سعر العرض'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OfferService', to='service.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ البدء'),
        ),
    ]
