# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('buyPrice', models.IntegerField(default=0)),
                ('sellPrice', models.IntegerField(default=0)),
                ('minLevel', models.IntegerField(default=0)),
                ('entryDate', models.DateTimeField(default=datetime.datetime.now)),
                ('expireDate', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to='staff.staff')),
            ],
        ),
    ]
#blank=True, null=True,