# Generated by Django 5.2.8 on 2025-11-19 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugin', '0001_initial'),
        ('staff', '0002_rename_phonespecialize_staff_phone_staff_specialize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugin',
            options={'verbose_name': 'دواء', 'verbose_name_plural': 'الادوية الداخلة'},
        ),
        migrations.AlterField(
            model_name='drugin',
            name='buyPrice',
            field=models.IntegerField(verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='entryDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الادخال'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='minLevel',
            field=models.IntegerField(verbose_name='الحد الادنى'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الدواء'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='sellPrice',
            field=models.IntegerField(verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DruginStaff', to='staff.staff', verbose_name='المدخل'),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='unit',
            field=models.CharField(max_length=200, verbose_name='الوحدة'),
        ),
    ]
