# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcomeDate', models.DateField(default=datetime.datetime.now)),
                ('outcomeType', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
