# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcomeDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcomeType',
            field=models.CharField(max_length=200, verbose_name='نوع المصروفات'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='total',
            field=models.IntegerField(verbose_name='المبلغ'),
        ),
    ]
