# Generated by Django 5.2.3 on 2025-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyprescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readyprescription',
            options={'verbose_name': 'وصفة جاهزة', 'verbose_name_plural': 'الوصفات الجاهزة'},
        ),
        migrations.AlterField(
            model_name='readyprescription',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الوصفة'),
        ),
    ]
