# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='DebtorDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
