# Generated by Django 5.2.3 on 2025-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(verbose_name='الكلفة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='السعر'),
        ),
    ]
