# Generated by Django 5.2.8 on 2025-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'دواء', 'verbose_name_plural': 'الادوية'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='عدد الايام'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الجرعة'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مرة كل يوم'),
        ),
    ]
