# Generated by Django 5.2.8 on 2025-11-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('readyprescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyPrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReadyPrescriptionDrugDrug', to='drug.drug')),
                ('readyPrescription_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReadyPrescriptionDrugReadyPrescription', to='readyprescription.readyprescription')),
            ],
        ),
    ]
