# Generated by Django 5.2.3 on 2025-11-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_drug_options_alter_drug_days_alter_drug_dose_and_more'),
        ('readyprescription', '0002_alter_readyprescription_options_and_more'),
        ('readyprescriptiondrug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readyprescriptiondrug',
            options={'verbose_name': 'دواء الوصفة', 'verbose_name_plural': 'ادوية الوصفات الجاهزة'},
        ),
        migrations.AlterField(
            model_name='readyprescriptiondrug',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReadyPrescriptionDrugDrug', to='drug.drug', verbose_name='الدواء'),
        ),
        migrations.AlterField(
            model_name='readyprescriptiondrug',
            name='readyPrescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReadyPrescriptionDrugReadyPrescription', to='readyprescription.readyprescription', verbose_name='الوصفة'),
        ),
    ]
