# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
import django.db.models.deletion
import fingerprint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrintMdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default=fingerprint.models.FingerPrintMdl.generate_random_string, max_length=32)),
                ('fdate', models.DateField(default=datetime.datetime.now)),
                ('timeRecord', models.TimeField(blank=True, null=True)),
                ('in_out', models.BooleanField(default=True)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff')),
            ],
        ),
    ]
