# Generated by Django 5.2.3 on 2025-11-19 16:27

import datetime
import django.db.models.deletion
import fingerprint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
        ('staff', '0002_rename_phonespecialize_staff_phone_staff_specialize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintmdl',
            name='barcode',
            field=models.CharField(default=fingerprint.models.FingerPrintMdl.generate_random_string, max_length=32, verbose_name='باركود'),
        ),
        migrations.AlterField(
            model_name='fingerprintmdl',
            name='fdate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='fingerprintmdl',
            name='in_out',
            field=models.BooleanField(default=True, verbose_name='دخول/خروج'),
        ),
        migrations.AlterField(
            model_name='fingerprintmdl',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='fingerprintmdl',
            name='timeRecord',
            field=models.TimeField(blank=True, null=True, verbose_name='الوقت'),
        ),
    ]
