# Generated by Django 5.2.3 on 2025-11-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0002_alter_fingerprintmdl_barcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerprintmdl',
            options={'verbose_name': 'بصمة', 'verbose_name_plural': 'بصمة الحضور والانصراف'},
        ),
    ]
