# Generated by Django 5.2.3 on 2025-11-16 22:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200)),
                ('creditorDetailsDate', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreditorDetails', to='creditor.creditor')),
            ],
        ),
    ]
