# Generated by Django 5.2.3 on 2025-11-17 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditordetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditordetails',
            name='creditorDetailsDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='creditordetails',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
