# Generated by Django 5.2.8 on 2025-11-19 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0003_alter_creditor_options_alter_creditor_client_id_and_more'),
        ('creditordetails', '0002_alter_creditordetails_creditordetailsdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditordetails',
            options={'verbose_name': 'تسديد', 'verbose_name_plural': 'تسديد الدائنين'},
        ),
        migrations.AlterField(
            model_name='creditordetails',
            name='amount',
            field=models.IntegerField(verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='creditordetails',
            name='creditorDetailsDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='creditordetails',
            name='creditor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreditorDetails', to='creditor.creditor', verbose_name='الدائن'),
        ),
        migrations.AlterField(
            model_name='creditordetails',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
    ]
