# Generated by Django 5.2.8 on 2025-11-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('sessionx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionDrugDrug', to='drug.drug')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionDrugSessionx', to='sessionx.sessionx')),
            ],
        ),
    ]
