# Generated by Django 5.2.3 on 2025-11-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_drug_options_alter_drug_days_alter_drug_dose_and_more'),
        ('sessiondrugs', '0001_initial'),
        ('sessionx', '0004_alter_sessionx_client_id_alter_sessionx_deletenote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiondrug',
            options={'verbose_name': 'دواء الجلسة', 'verbose_name_plural': 'ادوية الجلسات'},
        ),
        migrations.AlterField(
            model_name='sessiondrug',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionDrugDrug', to='drug.drug', verbose_name='الدواء'),
        ),
        migrations.AlterField(
            model_name='sessiondrug',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionDrugSessionx', to='sessionx.sessionx', verbose_name='الجلسة'),
        ),
    ]
