# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
        ('staff', '0003_alter_staff_options_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'مكافئة', 'verbose_name_plural': 'المكافئات'},
        ),
        migrations.AlterField(
            model_name='reward',
            name='gift',
            field=models.IntegerField(verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='rewardDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RewardStaff', to='staff.staff', verbose_name='الموظف'),
        ),
    ]
