# Generated by Django 5.2.3 on 2025-11-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options_alter_service_cost_and_more'),
        ('staff', '0003_alter_staff_options_alter_staff_address_and_more'),
        ('staffservicepercent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffservicpercent',
            options={'verbose_name': 'نسبة المظف', 'verbose_name_plural': 'نسب الموظفين'},
        ),
        migrations.AlterField(
            model_name='staffservicpercent',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='نسبة الموظف من الخدمة'),
        ),
        migrations.AlterField(
            model_name='staffservicpercent',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StaffServicPercentService', to='service.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='staffservicpercent',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StaffServicPercentStaff', to='staff.staff', verbose_name='الموظف'),
        ),
    ]
