# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('staff', '0003_alter_staff_options_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اشعار', 'verbose_name_plural': 'الاشعارات'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=200, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ndate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotificationStaff', to='staff.staff', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
