# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtor', '0002_alter_debtor_debtordate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('debtorDetailDate', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DebtorDetails', to='debtor.debtor')),
            ],
        ),
    ]
