# Generated by Django 5.2.8 on 2025-11-19 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0003_alter_debtor_options_alter_debtor_debtordate_and_more'),
        ('debtordetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtordetail',
            options={'verbose_name': 'تسديد', 'verbose_name_plural': 'تسديد المدينين'},
        ),
        migrations.AlterField(
            model_name='debtordetail',
            name='amount',
            field=models.IntegerField(verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='debtordetail',
            name='debtorDetailDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='debtordetail',
            name='debtor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DebtorDetails', to='debtor.debtor', verbose_name='المدين'),
        ),
        migrations.AlterField(
            model_name='debtordetail',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
    ]
