# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugin', '0001_initial'),
        ('sessionx', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('outDate', models.DateTimeField(default=datetime.datetime.now)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drugin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutDrugin', to='drugin.drugin')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutSessionx', to='sessionx.sessionx')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutStaff', to='staff.staff')),
            ],
        ),
    ]
