# Generated by Django 5.2.3 on 2025-11-19 16:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugin', '0002_alter_drugin_options_alter_drugin_buyprice_and_more'),
        ('drugout', '0001_initial'),
        ('sessionx', '0003_alter_sessionx_sessionstate'),
        ('staff', '0002_rename_phonespecialize_staff_phone_staff_specialize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugout',
            name='drugin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutDrugin', to='drugin.drugin', verbose_name='الدواء المدخل'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='outDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutSessionx', to='sessionx.sessionx', verbose_name='الجلسة'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugoutStaff', to='staff.staff', verbose_name='المدخل'),
        ),
    ]
