# Generated by Django 5.2.3 on 2025-11-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugout', '0002_alter_drugout_drugin_id_alter_drugout_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugout',
            options={'verbose_name': 'دواء', 'verbose_name_plural': 'الادوية الخارجة'},
        ),
    ]
