# Generated by Django 5.2.8 on 2025-11-19 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_alter_client_options_alter_client_address_and_more'),
        ('service', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionDate', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discountPrice', models.IntegerField(default=0)),
                ('newPrice', models.IntegerField(default=0)),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('sessionState', models.CharField(choices=[('تمت الجلسة', 'تمت الجلسة'), ('دفع مسبق', 'دفع مسبق'), ('انتظار', 'انتظار')], default='انتظار', max_length=200)),
                ('deviceConsumption', models.IntegerField(default=0)),
                ('paied', models.IntegerField(default=0)),
                ('nextSession', models.BooleanField(default=False)),
                ('nextSessionDate', models.DateField(default=datetime.datetime.now)),
                ('nextSessionNote', models.CharField(blank=True, max_length=200, null=True)),
                ('deleteRequest', models.BooleanField(default=False)),
                ('deleteNote', models.CharField(  max_length=200 )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxClient', to='client.client')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxService', to='service.service')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxStaff', to='staff.staff')),
            ],
        ),
    ]
