# Generated by Django 5.2.8 on 2025-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionx',
            name='sessionState',
            field=models.CharField(choices=[('تمت الجلسة', 'تمت الجلسة'), ('انتظار', 'انتظار'), ('دفع مسبق', 'دفع مسبق')], default='انتظار', max_length=200),
        ),
    ]
