# Generated by Django 5.2.3 on 2025-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionx', '0002_alter_sessionx_sessionstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionx',
            name='sessionState',
            field=models.CharField(choices=[('تمت الجلسة', 'تمت الجلسة'), ('دفع مسبق', 'دفع مسبق'), ('انتظار', 'انتظار')], default='انتظار', max_length=200),
        ),
    ]
