# Generated by Django 5.2.3 on 2025-11-19 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_blood_alter_client_mariage'),
        ('service', '0002_alter_service_options_alter_service_cost_and_more'),
        ('sessionx', '0003_alter_sessionx_sessionstate'),
        ('staff', '0003_alter_staff_options_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionx',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxClient', to='client.client', verbose_name='الزبون'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='deleteNote',
            field=models.CharField(max_length=200, verbose_name='سبب الحذف'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='deleteRequest',
            field=models.BooleanField(default=False, verbose_name='طلب الحذف'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='deviceConsumption',
            field=models.IntegerField(default=0, verbose_name='استهلاك الجهاز'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التشخيص'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='discountPrice',
            field=models.IntegerField(default=0, verbose_name='مبلغ الخصم'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='newPrice',
            field=models.IntegerField(default=0, verbose_name='السعر بعد الخصم'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='nextSession',
            field=models.BooleanField(default=False, verbose_name='جلسة قادمة؟'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='nextSessionDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الجلسة القادمة'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='nextSessionNote',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظات الجلسة القادمة'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='paied',
            field=models.IntegerField(default=0, verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='price',
            field=models.IntegerField(default=0, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxService', to='service.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='sessionDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الجلسة'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='sessionState',
            field=models.CharField(choices=[('دفع مسبق', 'دفع مسبق'), ('تمت الجلسة', 'تمت الجلسة'), ('انتظار', 'انتظار')], default='انتظار', max_length=200, verbose_name='حالة الجلسة'),
        ),
        migrations.AlterField(
            model_name='sessionx',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionxStaff', to='staff.staff', verbose_name='الموظف'),
        ),
    ]
